### PR TITLE
chore: replaced map with forEach

### PR DESCRIPTION
**Pull request by ShashwatPS**
Description :

- Removed the map function with forEach in examples/angular/src/test.ts
Related issue(s) :

- Resolves Remove this commented out code. https://github.com/asyncapi/EDAVisualiser/issues/32

### CODE REVIEW

**Review by jonaslagoni — APPROVED** [review]
Thanks @ShashwatPS 👍

**Comment by jonaslagoni** [comment]
@all-contributors please add @ShashwatPS for code

**Comment by ShashwatPS** [comment]
If possible can you add the Hacktoberfest label too ?

**Pull request merged**
